# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Discretos
tagline:          'Discretamente'
description:      'Discretamente...'
url:              http://discretos.github.io
baseurl:          /

author:
  name:           'Dizando Norton'
  url:            https://twitter.com/dizandonorton

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/discretos
